### ISSUE TITLE
Setting widget_remove_btn has to be set in options. 

### ISSUE THREAD

**Issue by Misiur** [phiamo/MopaBootstrapSandboxBundle#43]
https://github.com/phiamo/MopaBootstrapSandboxBundle/blob/50b5a1d00f9b0cc9de27dc5b199822423976f3c7/Form/Type/ExampleCollectionsFormType.php#L29

This example won't work. For some reason it will only work when specified in ```options``` and gets passed to child options. Is it feature or a bug? Synax used in example looks nicer (same options level as add_btn), but the current one makes more sense logically (remove button is specific for each child).

**Comment by phiamo** [comment]
@Misiur the remove button has to be with each child, the add button for the colleciton itself ...
